services:
  - type: web
    name: kibua-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class sync --workers=4 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
