services:
  - type: web
    name: kibua-system
    env: python
    region: frankfurt       # או כל אזור אחר שתבחר
    plan: starter
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn "run:create_app()" --bind 0.0.0.0:10000
    pythonVersion: 3.11
